stage: "prod"

microservices:
  app:
    pullPolicy: Always
    replicaCount: 1
    imagePullSecrets: "ylab-gitlab-registry"
    updateStrategy: RollingUpdate
    revisionHistoryLimit: 5
    ports:
      http: 8000
    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 0.1
        memory: 256Mi
    service:
      port: 8000
      type: ClusterIP
    ingress:
      enabled: false